name: 'crowdin-elixir-action'

description: 'Tries to manage and synchronize Crowdin'

inputs:
  organization:
    description: 'Crowdin organization'
    required: false
  project_id:
    description: 'Crowdin project id'
    required: true
  source_file:
    description: 'Crowdin source file'
    required: true
  source_files:
    description: 'Crowdin source files'
    required: true
  export_pattern:
    description: 'Crowdin source export pattern'
    required: true
  base_branch:
    description: 'Base branch for pull request'
    required: true
    default: 'master'
  update_source:
    description: 'Update source to crowdin'
    required: false
  update_translation:
    description: 'Update translation from crowdin'
    required: false
  skip_untranslated_strings:
    description: 'Skip untranslated strings'
    required: true
    default: 'false'
  export_approved_only:
    description: 'Export only approved strings'
    required: true
    default: 'false'
runs:
  using: docker
  image: 'Dockerfile'
