name: 'crowdin-elixir-action'

description: 'Tries to manage and synchronize Crowdin'

inputs:
  organization:
    description: 'Crowdin organization'
    required: false
  project_id:
    description: 'Crowdin project id'
    required: true
  source_file:
    description: 'Crowdin source file, can have optional format source_file:export_pattern:source_file_name'
    required: true
  export_pattern:
    description: 'Crowdin source export pattern'
    required: true
  base_branch:
    description: 'Base branch for pull request'
    required: true
    default: 'master'
  update_source:
    description: 'Update source to crowdin'
    required: false
  update_translation:
    description: 'Update translation from crowdin'
    required: false
  skip_untranslated_strings:
    description: 'Skip untranslated strings'
    required: true
    default: 'false'
  export_approved_only:
    description: 'Export only approved strings'
    required: true
    default: 'false'
  front_end_context:
    description: 'Front-end tweak to provide context'
    required: false
    default: 'false'
  automatic_merge_pr:
    description: 'Automatic merge PR'
    required: false
    default: 'false'
  crowdin_token:
    description: 'Token used to make crowdin requests'
    required: false
  github_api_token:
    description: 'Token used to make github API requests(create PR), if not set, GITHUB_TOKEN will be used and created PR will not trigger another workflow.'
    required: false
runs:
  using: docker
  image: 'Dockerfile'
